### ISSUE TITLE
Genesis 3.0 admin page removal

### ISSUE THREAD

**Issue by rothbert** [billerickson/BE-Genesis-Theme-Settings#2]
Hi Bill - really appreciate this plugin as the customizer version is a real regression in UX. 
I see that the Theme and SEO setting page is now gone completely from Genesis 3.0.x ...
Any plans to extend this plugin to add it back? 
Thanks

**Comment by billerickson** [comment]
Unfortunately no, that functionality was removed in Genesis 3.0 so cannot be added back by this plugin. If you want to keep the theme settings page, you need to downgrade Genesis 2.10

**Comment by rothbert** [comment]
OK, thanks Bill
